name: Build & Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: npm install

      - name: 构建打包
        run: npm run build

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: build/**/*
